# Netlify configuration for static front-end
[build]
  command = ""
  publish = "public"

# Placeholder redirect to Render backend; update `to` after Render deployment
# Uncomment and replace YOUR_RENDER_URL with actual backend URL
# [[redirects]]
#   from = "/api/*"
#   to = "https://YOUR_RENDER_URL/api/:splat"
#   status = 200
